# Generated by Django 5.2.1 on 2025-05-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('FI', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('RefNo', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Officer', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=15)),
                ('Department', models.CharField(max_length=25)),
                ('ContactNumber', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IncidentStatus',
            fields=[
                ('StatusId', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(choices=[('U', 'Active'), ('F', 'False'), ('A', 'Resolved')], default='U', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('Institution_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('BRN', models.IntegerField()),
                ('Address', models.CharField(max_length=255)),
                ('ContactEmail', models.EmailField(max_length=254)),
                ('ContactPhone', models.IntegerField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
