# Generated by Django 5.2.1 on 2025-05-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentstatus',
            name='Status',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'False'), ('R', 'Resolved')], default='A', max_length=1),
        ),
    ]
